apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: python-custom-autoscaler-cpa
spec:
  template:
    spec:
      containers:
      - name: pca-hpa
        image: vahidmostofi/pca-hpa-test:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  config:
    - name: interval
      value: "10000"